services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../../.env.development
    ports:
      # HOST:CONTAINER (DEFAULT POSTGRES VALUE)
      - "5333:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data

volumes:
  postgres_dev:
